/*
  Copyright 2010, 2011 Genuitec, LLC
  Licensed under the MobiOne Studio End User License, (the "License");
  This header will appear in all HTML files generated by MobiOne Studio(tm)
  operating in "trial" mode.  While in trial mode, you may only use
  MobiOne for evaluation.  You may not use the trial version of MobiOne
  for any commercial, enterprise or corporate (for profit or nonprofit)
  purpose unless expressly licensed to do otherwise.  You may not modify
  or remove this header for any reason prior to purchasing and activating
  a license for MobiOne.  Upon activation,  MobiOne will not generate
  this header.  You may obtain a copy of the MobiOne License at
  
  http://genuitec.com/mobile/mobione/1.0/LICENSE.html
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
var m1Design = function() { m1Design = {}; var c=m1Design;var e="m1-";var f=function(d){return e+d};var g="dev";var h="dev.html";var i="dev.css";var j="dev_custom.js";var k={dev:{id:g,anchor_id:"#m1-dev",dynamic:false,html_url:function(){return h},css_url:function(){return i},js_url:function(){return j},resize:function(d,b){var a;var M={};var N}}};var l="document";var m="body";var n="createElement";var o="a";var p="innerText";var q="Created by MobiOne Studio - Free Trial";var r="href";var s="http://genuitec.com/mobile/buy.html";var t="style";
var u="position";var v="absolute";var w="fontFamily";var x="Helvetica";var y="fontSize";var z="9px";var A="color";var B="red";var C="top";var D="0px";var E="left";var F="width";var G="98%";var H="textAlign";var I="right";var J="zIndex";var K="1000";var L="appendChild";window["addEventListener"]("load",function(){var d=window[l][m];var b=window[l][n](o);b[p]=q;b[r]=s;var a=b[t];a[u]=v;a[w]=x;a[y]=z;a[A]=B;a[C]=D;a[E]=D;a[F]=G;a[H]=I;a[J]=K;d[L](b)});c["css"]=f;c["pages"]=k;
c["shouldHideAddressBar"]=true;c["root"]=function(){return g}; return m1Design; }();